# Copyright 2026, IBM Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Structural checks on the Sphinx documentation source.

These are deliberately static: they parse the ``.rst``/``.md`` sources and the CI
workflow rather than running ``sphinx-build``, so they hold in an environment
where the ``[docs]`` extra is not installed (the common case for a contributor
running ``pytest``). An executed-build test belongs in
``tests/integration/test_docs_build.py`` behind ``importorskip("sphinx")``.

What they catch is exactly what went wrong before:

* an API reference reachable by no toctree, so every page was an orphan
* toctree entries naming files that were never added
* ``automodule`` directives naming modules that do not exist
* ``conf.py`` paths that only resolve when ``sphinx-build`` runs from ``docs/``
* a documented version that disagrees with ``qbiocode/version.py``
* rendered HTML committed back into the repository
* a tutorial notebook added under ``tutorial/`` and never linked from a toctree

``docs/source/tutorials/`` is generated by ``_sync_tutorials()`` in ``conf.py`` and
is absent until a build runs, so these checks resolve ``tutorials/<x>`` toctree
entries against the repository's ``tutorial/<x>`` source instead of against the
derived copy. That keeps them deterministic: they give the same answer on a clean
checkout and after a build.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
SOURCE_DIR = DOCS_DIR / "source"

#: Mirrors ``exclude_patterns`` in ``conf.py``. ``workshops/_tutorial.rst`` is a
#: ``{{placeholder}}`` skeleton for authoring new workshop pages, not a page.
EXCLUDED = {"workshops/_tutorial.rst"}

#: Documents Sphinx reaches without a toctree entry.
IMPLICIT_ROOTS = {"index.rst"}

#: The generated tutorial tree, and the repository directory it is derived from.
#: ``conf.py``'s ``_sync_tutorials()`` copies the second into the first at
#: ``builder-inited``; nothing under ``docs/source/tutorials/`` is authored or
#: tracked.
GENERATED_TUTORIALS = "tutorials/"
TUTORIAL_SOURCE = REPO_ROOT / "tutorial"

#: A page may opt out of the orphan warning explicitly: ``:orphan:`` as a field in
#: reStructuredText, ``orphan: true`` in MyST front matter. Honour that rather than
#: forcing every such page into a toctree.
_ORPHAN_MARKERS = (":orphan:", "orphan: true")


def _declares_itself_orphan(rel: str) -> bool:
    if rel.endswith(".ipynb"):
        return False
    head = (SOURCE_DIR / rel).read_text(encoding="utf-8")[:512]
    return any(marker in head for marker in _ORPHAN_MARKERS)


DOC_SUFFIXES = (".rst", ".md", ".ipynb")


def _iter_documents():
    """Every file Sphinx would treat as a document, as source-relative posix paths."""
    for path in sorted(SOURCE_DIR.rglob("*")):
        if not path.is_file() or path.suffix not in DOC_SUFFIXES:
            continue
        rel = path.relative_to(SOURCE_DIR).as_posix()
        # ``tutorials/`` is skipped because it is derived and may or may not exist
        # depending on whether a build has run here; the notebooks behind it are
        # checked at their real location by TestGeneratedTutorialTree.
        if rel in EXCLUDED or rel.startswith(
            ("build/", "_static/", ".ipynb_checkpoints/", GENERATED_TUTORIALS)
        ):
            continue
        if ".ipynb_checkpoints/" in rel:
            continue
        yield rel


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip())


def _toctree_entries(text: str):
    """Yield the raw entries of every toctree in ``text``.

    Handles both the reStructuredText ``.. toctree::`` directive and the MyST
    ```` ```{toctree} ```` fence, and skips option lines (``:maxdepth: 2``) and
    the blank line that follows them -- a naive "indented block" regex stops at
    that blank line and reports every entry as missing.

    The RST body ends at the first non-blank line indented no further than the
    directive itself, which is the actual reStructuredText rule. It used to end
    only at column 0, and that silently held for as long as every toctree in the
    tree sat at column 0. ``better_apidoc`` broke it: the pages it generates put
    the whole body -- ``Submodules:`` toctree, then ``Summary`` list-tables --
    indented under a top-level ``.. automodule::``, so nothing ever dedents to
    column 0. The parser ran off the end of the file and yielded every list-table
    row as a toctree entry, including a dataclass ``__repr__`` long enough to
    raise ``OSError: File name too long`` when the existence check stat()ed it.
    """
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        rst = line.strip() == ".. toctree::"
        myst = line.strip().startswith("```{toctree}")
        if not (rst or myst):
            i += 1
            continue
        directive_indent = _indent_of(line)
        i += 1
        while i < len(lines):
            entry = lines[i]
            stripped = entry.strip()
            if myst and stripped.startswith("```"):
                break
            if rst and stripped and _indent_of(entry) <= directive_indent:
                break  # dedented back out of the directive body
            i += 1
            if not stripped or stripped.startswith(":"):
                continue  # blank line or directive option
            yield stripped


def _resolve(entry: str, containing_doc: str):
    """Turn one toctree entry into a source-relative path, or None if not a document."""
    # "Some Title <path/to/doc>" -> "path/to/doc"
    match = re.search(r"<([^>]+)>\s*$", entry)
    target = match.group(1) if match else entry
    if target.startswith(("http://", "https://", "self", "genindex", "modindex", "search")):
        return None
    if "*" in target or "?" in target:
        return None  # glob entry; existence is Sphinx's problem, not ours
    base = os.path.dirname(containing_doc)
    return os.path.normpath(os.path.join(base, target)).replace(os.sep, "/")


def _document_exists(target: str) -> bool:
    """Does a toctree target name a real document?

    A ``tutorials/...`` target is checked against ``tutorial/...`` in the
    repository root, since the copy under ``docs/source/`` only comes into
    existence when ``_sync_tutorials()`` runs during a build.
    """
    if target.startswith(GENERATED_TUTORIALS):
        rest = target[len(GENERATED_TUTORIALS) :]
        return (
            any((TUTORIAL_SOURCE / f"{rest}{suffix}").exists() for suffix in DOC_SUFFIXES)
            or (TUTORIAL_SOURCE / rest).exists()
        )
    return (
        any((SOURCE_DIR / f"{target}{suffix}").exists() for suffix in DOC_SUFFIXES)
        or (SOURCE_DIR / target).exists()
    )


def _mocked_imports():
    r"""The names in ``autodoc_mock_imports``, parsed a line at a time.

    Not a single bracket regex: the list carries comments, and one of them is
    ``# [quvine] extra`` -- a non-greedy ``\[(.*?)\]`` stops at that ``]`` and
    reports an empty list, which would make this check vacuously pass.
    """
    lines = (SOURCE_DIR / "conf.py").read_text(encoding="utf-8").splitlines()
    names = set()
    collecting = False
    for line in lines:
        if not collecting:
            if re.match(r"^autodoc_mock_imports\s*=\s*\[", line):
                collecting = True
                line = line.split("[", 1)[1]
            else:
                continue
        code = line.split("#", 1)[0]
        names.update(re.findall(r"[\"']([^\"']+)[\"']", code))
        if "]" in code:
            break
    return names


def _reachable_documents():
    """Map every document reachable from a toctree to the document that includes it."""
    reachable = {}
    for doc in _iter_documents():
        if doc.endswith(".ipynb"):
            continue  # notebooks contain no toctrees
        text = (SOURCE_DIR / doc).read_text(encoding="utf-8")
        for entry in _toctree_entries(text):
            target = _resolve(entry, doc)
            if target is not None:
                reachable.setdefault(target, doc)
    return reachable


class TestToctree:
    def test_every_toctree_entry_names_an_existing_document(self):
        """A toctree entry with no file behind it is a build warning and a dead link."""
        dangling = []
        for target, source in sorted(_reachable_documents().items()):
            if not _document_exists(target):
                dangling.append(f"{target} (referenced from {source})")
        assert not dangling, "toctree entries with no document:\n  " + "\n  ".join(dangling)

    def test_no_document_is_orphaned(self):
        """Every page must be reachable by navigation.

        The whole of ``api/`` used to fail this: nothing pointed at ``api/modules``,
        so the API reference was reachable only by guessing a URL.
        """
        reachable = _reachable_documents()
        orphans = []
        for doc in _iter_documents():
            if doc in IMPLICIT_ROOTS or _declares_itself_orphan(doc):
                continue
            stem = doc.rsplit(".", 1)[0]
            if stem in reachable or doc in reachable:
                continue
            orphans.append(doc)
        assert (
            not orphans
        ), "documents in no toctree (Sphinx warns, and -W fails the build):\n  " + "\n  ".join(
            sorted(orphans)
        )

    def test_the_api_reference_is_rooted(self):
        """Guards the specific regression: api/modules reachable from api_overview."""
        assert "api/modules" in _reachable_documents()

    def test_an_indented_toctree_ends_where_the_directive_body_ends(self):
        """A nested toctree must not swallow whatever follows it.

        ``better_apidoc`` indents a whole page under one ``.. automodule::``, so a
        toctree in it never dedents to column 0. The parser used to read to the
        end of the file and report the ``Summary`` list-table's rows as toctree
        entries -- one of which was a dataclass ``__repr__`` long enough that
        stat()ing it as a filename raised ``OSError``.
        """
        page = (
            ".. automodule:: pkg\n"
            "\n"
            "    Submodules:\n"
            "\n"
            "    .. toctree::\n"
            "       :maxdepth: 1\n"
            "\n"
            "       pkg.real_submodule\n"
            "\n"
            "    Summary\n"
            "    -------\n"
            "\n"
            "    .. list-table::\n"
            "\n"
            "       * - :class:`Config <pkg.mod.Config>`\n"
            "         - Config(a: 'int' = 1, b: 'str' = 'x')\n"
        )
        assert list(_toctree_entries(page)) == ["pkg.real_submodule"]


class TestApiPages:
    def test_every_automodule_target_exists(self):
        """An ``automodule`` for a module that was renamed or removed documents nothing."""
        missing = []
        for page in sorted((SOURCE_DIR / "api").glob("*.rst")):
            text = page.read_text(encoding="utf-8")
            for target in re.findall(r"^\.\.\s+automodule::\s+(\S+)", text, re.M):
                parts = target.split(".")
                as_module = REPO_ROOT.joinpath(*parts).with_suffix(".py")
                as_package = REPO_ROOT.joinpath(*parts, "__init__.py")
                if not (as_module.exists() or as_package.exists()):
                    missing.append(f"{target} (in {page.name})")
        assert not missing, "automodule targets that do not exist:\n  " + "\n  ".join(missing)

    @pytest.mark.parametrize(
        "module",
        [
            "qbiocode.apps",
            "qbiocode.apps.quvine",
            "qbiocode.apps.qprofiler",
            "qbiocode.evaluation.graph_evaluation",
            "qbiocode.utils.tutorial_data",
        ],
    )
    def test_new_public_modules_have_a_page(self, module):
        """``qbiocode.apps`` had no page at all, so QuVINE was absent from the API docs."""
        pages = list((SOURCE_DIR / "api").glob("*.rst"))
        directives = "\n".join(p.read_text(encoding="utf-8") for p in pages)
        assert f"automodule:: {module}\n" in directives, f"{module} is undocumented"


class TestConfPy:
    """``conf.py`` used to build every path from ``"."``, so it only worked from ``docs/``."""

    def test_paths_are_anchored_on_file_not_cwd(self):
        text = (SOURCE_DIR / "conf.py").read_text(encoding="utf-8")
        assert "os.path.abspath(__file__)" in text
        assert "_REPO_ROOT" in text and "_DOCS_DIR" in text and "_CONF_DIR" in text
        # A bare "." as a sys.path entry or a template/output directory is the bug.
        assert 'sys.path.insert(0, ".")' not in text
        assert '"-t", "./' not in text and "'-t', './" not in text

    def test_version_matches_the_package(self):
        """conf.py hardcoded 0.0.1 while the package declared 0.1.0."""
        conf = (SOURCE_DIR / "conf.py").read_text(encoding="utf-8")
        assert re.search(
            r"^release\s*=\s*_package_version\(\)", conf, re.M
        ), "release must be read from qbiocode/version.py, not hardcoded"
        version_py = (REPO_ROOT / "qbiocode" / "version.py").read_text(encoding="utf-8")
        declared = re.search(r"^__version__\s*=\s*[\"']([^\"']+)[\"']", version_py, re.M)
        assert declared, "qbiocode/version.py declares no __version__"
        # And the parser in conf.py must agree with that literal.
        namespace = {"__file__": str(SOURCE_DIR / "conf.py")}
        exec(  # noqa: S102 - executing our own conf.py is the point
            "\n".join(
                [
                    "import os, re",
                    "_CONF_DIR = os.path.dirname(os.path.abspath(__file__))",
                    "_REPO_ROOT = os.path.dirname(os.path.dirname(_CONF_DIR))",
                    re.search(r"^def _package_version\(\):.*?(?=^\S)", conf, re.M | re.S).group(0),
                    "parsed = _package_version()",
                ]
            ),
            namespace,
        )
        assert namespace["parsed"] == declared.group(1)

    def test_mocks_cover_the_quvine_extra_and_nothing_imaginary(self):
        names = _mocked_imports()
        assert names, "autodoc_mock_imports is not a literal list of names"
        # Every [quvine] import name must be mocked, or a docs build without the
        # extra cannot import the modules it is documenting.
        from qbiocode.apps.quvine._deps import OPTIONAL_DEPENDENCIES

        assert (
            set(OPTIONAL_DEPENDENCIES) <= names
        ), f"unmocked optional imports: {sorted(set(OPTIONAL_DEPENDENCIES) - names)}"
        # TensorFlow appears nowhere in the tree; mocking it hid that fact.
        assert "tensorflow" not in names and "keras" not in names


class TestNoBuildOutputInGit:
    def test_no_rendered_html_is_tracked(self):
        """~250 files of Sphinx output were once committed under docs/_build/html/."""
        try:
            tracked = subprocess.run(
                ["git", "ls-files", "docs/_build", "docs/build"],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                check=True,
            ).stdout.split()
        except (OSError, subprocess.CalledProcessError):
            pytest.skip("not a git checkout")
        assert not tracked, f"build output is tracked: {tracked[:5]}"

    def test_both_build_directories_are_ignored(self):
        ignored = (REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
        assert "docs/build/" in ignored
        assert "docs/_build/" in ignored


class TestGeneratedTutorialTree:
    """``docs/source/tutorials/`` is derived from ``tutorial/``, and stays derived.

    The two used to be hand-maintained copies of each other, and they drifted:
    ``sc_binary_qprofiler.ipynb`` grew a modality on the docs side only,
    ``qsage.ipynb``'s data fixture existed only on the docs side so the
    ``tutorial/`` copy could not run, and two notebooks lived under docs and
    nowhere else. Nothing warned, because both copies were valid documents.

    These checks are what makes the collapse stick: the generated tree must stay
    untracked and ignored, and every notebook in the one real tree must be
    published.
    """

    @staticmethod
    def _tutorial_notebooks():
        return sorted(
            path.relative_to(TUTORIAL_SOURCE).as_posix()
            for path in TUTORIAL_SOURCE.rglob("*.ipynb")
            if ".ipynb_checkpoints" not in path.parts
        )

    def test_nothing_under_the_generated_tree_is_tracked(self):
        """A tracked file here is the start of the next divergence.

        It would also be silently overwritten: ``_sync_tutorials()`` deletes and
        rebuilds the directory on every build.
        """
        try:
            tracked = subprocess.run(
                ["git", "ls-files", "docs/source/tutorials"],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                check=True,
            ).stdout.split()
        except (OSError, subprocess.CalledProcessError):
            pytest.skip("not a git checkout")
        assert not tracked, (
            "generated tutorial pages are tracked, so tutorial/ is no longer the "
            f"single source: {tracked[:5]}"
        )

    def test_the_generated_tree_is_ignored(self):
        ignored = (REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
        assert (
            "/docs/source/tutorials/" in ignored
        ), ".gitignore must exclude the generated tutorial tree"
        try:
            check = subprocess.run(
                ["git", "check-ignore", "-q", "docs/source/tutorials/QSage/qsage.ipynb"],
                cwd=REPO_ROOT,
                capture_output=True,
            )
        except OSError:
            pytest.skip("git is not available")
        assert check.returncode == 0, (
            "git does not consider the generated tutorial tree ignored; a later "
            "negation rule may be cancelling the exclusion"
        )

    def test_every_tutorial_notebook_is_published(self):
        """Add a notebook to ``tutorial/``, forget the toctree, and ``-W`` fails.

        The sync hook copies whatever is in ``tutorial/``, so an unreferenced
        notebook becomes a document Sphinx reaches from no toctree -- an
        "isn't included in any toctree" warning, and therefore a failed build,
        long after the notebook was added. Caught here instead.
        """
        published = {
            target[len(GENERATED_TUTORIALS) :] + ".ipynb"
            for target in _reachable_documents()
            if target.startswith(GENERATED_TUTORIALS)
        }
        unpublished = sorted(set(self._tutorial_notebooks()) - published)
        assert not unpublished, (
            "notebooks under tutorial/ that no toctree entry names (they would be "
            f"copied into the build and warn as orphans): {unpublished}"
        )

    def test_conf_py_generates_the_tree_safely(self):
        conf = (SOURCE_DIR / "conf.py").read_text(encoding="utf-8")
        assert (
            'app.connect("builder-inited", _sync_tutorials)' in conf
        ), "the sync hook is not wired up, so no tutorial page would be built"
        # The marker guard is the reason this hook is allowed to rmtree at all.
        assert "_TUTORIAL_MARKER" in conf and "shutil.rmtree" in conf
        # tutorial/QEnsemble/README.md must not be copied: myst_parser would read
        # it as a document in no toctree, which -W turns into a failed build.
        suffixes = re.search(r"_TUTORIAL_SUFFIXES\s*=\s*[^\n]+", conf)
        assert suffixes, "conf.py declares no _TUTORIAL_SUFFIXES"
        assert ".md" not in re.findall(r"[\"']([^\"']+)[\"']", suffixes.group(0)), (
            "copying .md into docs/source/tutorials/ makes tutorial/QEnsemble/"
            "README.md a document in no toctree, which -W fails the build on"
        )


class TestPublishedNotebooks:
    """Guards on the notebooks that become pages of the published site.

    ``nbsphinx_execute = 'never'``, so whatever a notebook carries in its committed
    JSON is what GitHub Pages serves. Two things have gone wrong that way.
    """

    #: Notebooks that become site pages. ``_static/workshops/`` is third-party Qiskit
    #: material offered as a download, not a rendered page, so it is out of scope.
    #:
    #: One entry, not two: ``docs/source/tutorials/`` used to be a second copy of
    #: these same notebooks and is now generated from this one at build time, so
    #: scanning it would either double-count every notebook or, on a clean
    #: checkout, find nothing there at all.
    NOTEBOOK_DIRS = ("tutorial",)

    @staticmethod
    def _notebooks():
        for rel in TestPublishedNotebooks.NOTEBOOK_DIRS:
            yield from sorted((REPO_ROOT / rel).rglob("*.ipynb"))

    def test_no_notebook_carries_dead_ipywidgets_state(self):
        """``metadata.widgets`` with no widget output fails ``sphinx-build -W``.

        A tqdm progress bar registers widget state even when its output renders as
        plain text. nbsphinx then warns ``nbsphinx_widgets_path not given and
        ipywidgets module unavailable`` -- fatal under ``-W`` -- and the state itself
        was 127 KB of never-rendered JSON in one notebook. Strip
        ``metadata.widgets``; do not add ipywidgets to the docs extra to silence it.
        """
        offenders = []
        for path in self._notebooks():
            notebook = json.loads(path.read_text(encoding="utf-8"))
            if "widgets" not in notebook.get("metadata", {}):
                continue
            rendered = sum(
                1
                for cell in notebook["cells"]
                for output in cell.get("outputs", [])
                if "application/vnd.jupyter.widget-view+json" in output.get("data", {})
            )
            if not rendered:
                offenders.append(path.relative_to(REPO_ROOT).as_posix())
        assert not offenders, f"dead metadata.widgets in: {offenders}"

    def test_no_notebook_publishes_an_absolute_local_path(self):
        """Committed output once named the author's home directory on every page.

        Useless to a reader (it names a directory that does not exist on their
        machine) and a needless disclosure of one machine's layout. Placeholders
        (``<env>/``, ``<repo>/``) are the substitute.
        """
        leak = re.compile(r"/(?:Users|home)/[A-Za-z0-9_.-]+|/private/tmp/")
        offenders = []
        for path in self._notebooks():
            found = sorted(set(leak.findall(path.read_text(encoding="utf-8"))))
            if found:
                offenders.append((path.relative_to(REPO_ROOT).as_posix(), found))
        assert not offenders, f"absolute local paths in notebooks: {offenders}"


class TestCiWorkflow:
    @staticmethod
    def _workflow():
        import yaml

        path = REPO_ROOT / ".github" / "workflows" / "ci.yml"
        return yaml.safe_load(path.read_text(encoding="utf-8"))

    def test_docs_build_failure_fails_ci(self):
        """The build step carried continue-on-error, so broken docs went unnoticed."""
        steps = self._workflow()["jobs"]["docs"]["steps"]
        build = next(s for s in steps if s.get("name") == "Build documentation")
        assert not build.get("continue-on-error", False)

    def test_deploy_is_gated_to_pushes_on_main(self):
        """A pull request -- including one from a fork -- must not publish the site."""
        job = self._workflow()["jobs"]["deploy-docs"]
        condition = job["if"]
        assert "github.event_name == 'push'" in condition
        assert "refs/heads/main" in condition
        assert job["needs"] == "docs" or "docs" in job["needs"]

    def test_deploy_writes_nojekyll(self):
        """Without it, Pages drops every _-prefixed Sphinx directory."""
        steps = self._workflow()["jobs"]["deploy-docs"]["steps"]
        assert any(".nojekyll" in str(step.get("run", "")) for step in steps)


# Config keys the shipped config.yaml offers that the documentation never mentions.
# Each entry is a debt record rather than a permanent exemption -- document the key and
# delete its line. All of these predate the Optuna work; the point of the assertion below
# is that the list does not grow.
UNDOCUMENTED_CONFIG_KEYS = {
    "NN_depth",
    "dt_args",
    "gridsearch_dt_args",
    "gridsearch_lr_args",
    "gridsearch_mlp_args",
    "gridsearch_nb_args",
    "lr_args",
    "mlp_args",
    "multi_class",
    "nb_args",
}


class TestEveryConfigKeyIsDocumented:
    """A key you can set but cannot look up is a key nobody will use correctly.

    Adding a config key and forgetting the docs is invisible: the key works, the yaml
    parses, and the only symptom is a user who cannot find out what it does. This caught
    exactly that -- `tune_quantum` and friends were documented, but the five
    `gridsearch_<quantum model>_args` block names, both projection-cache directories and
    the `BestParams_Tuned` results column were not.
    """

    @staticmethod
    def _documentation():
        return "\n".join(
            path.read_text(encoding="utf-8")
            for path in sorted((DOCS_DIR / "source").rglob("*"))
            if path.suffix in {".md", ".rst"}
        )

    @staticmethod
    def _shipped_keys():
        import yaml

        config = yaml.safe_load(
            (REPO_ROOT / "qbiocode" / "apps" / "qprofiler" / "configs" / "config.yaml").read_text(
                encoding="utf-8"
            )
        )
        # `hydra` is the runner's own block, not a QBioCode setting.
        return {key for key in config if key != "hydra"}

    def test_no_new_config_key_is_undocumented(self):
        documentation = self._documentation()
        missing = {key for key in self._shipped_keys() if key not in documentation}
        unexpected = missing - UNDOCUMENTED_CONFIG_KEYS
        assert not unexpected, (
            "config.yaml keys that appear nowhere in docs/source: "
            f"{sorted(unexpected)}. Document them, or add them to "
            "UNDOCUMENTED_CONFIG_KEYS with the intent to."
        )

    def test_the_debt_list_has_no_stale_entries(self):
        """A documented key left on the list makes the list stop meaning anything."""
        documentation = self._documentation()
        shipped = self._shipped_keys()
        stale = {
            key for key in UNDOCUMENTED_CONFIG_KEYS if key not in shipped or key in documentation
        }
        assert not stale, (
            f"UNDOCUMENTED_CONFIG_KEYS entries that are now documented (or gone from "
            f"config.yaml): {sorted(stale)}. Delete them from the list."
        )


class TestTheModelDocsMatchTheCode:
    """Prose about the models, checked against the models.

    Added after the documentation drifted twice in one change: TabPFN was pinned to the
    commercially-usable ``v2`` weights, which need no API token and no license acceptance,
    but ``README.md``, ``profiler.rst``, ``tutorials.md``, two requirements files and the
    conda recipe all still said a license acceptance was required. Nothing failed, because
    nothing was checking. A stale requirement in a README is worse than an undocumented
    one -- it sends a reader off to satisfy a condition that no longer exists, or worse,
    to accept a licence they did not need to accept.
    """

    #: Docs a user reads before running anything.
    USER_FACING = (
        "README.md",
        "docs/source/installation.md",
        "docs/source/apps/config.md",
        "docs/source/apps/profiler.rst",
        "docs/source/tutorials.md",
    )

    @staticmethod
    def _text(relative):
        return (REPO_ROOT / relative).read_text(encoding="utf-8")

    @staticmethod
    def _dispatch_keys():
        """The model names ``model_run`` accepts, read out of its own table."""
        source = (REPO_ROOT / "qbiocode" / "evaluation" / "model_run.py").read_text()
        block = source.split("compute_ml_dict = {")[1].split("}")[0]
        keys = re.findall(r'"([a-z_0-9]+)":\s*compute_', block)
        assert keys, "could not read compute_ml_dict out of model_run.py"
        return {k for k in keys if not k.endswith("_opt")}

    def test_every_dispatchable_model_is_in_the_config_table(self):
        """The table in config.md is where a user picks names for ``model:``."""
        table = self._text("docs/source/apps/config.md")
        missing = sorted(name for name in self._dispatch_keys() if f"`{name}`" not in table)
        assert not missing, (
            f"models accepted by model_run but absent from the model table in "
            f"docs/source/apps/config.md: {missing}"
        )

    @pytest.mark.parametrize("relative", USER_FACING)
    def test_no_document_demands_a_tabpfn_token_without_saying_the_default_needs_none(
        self, relative
    ):
        """The exact drift that happened: 'TabPFN requires a license acceptance', full stop.

        It is true only of the opt-in ``v2.5``/``v2.6``/``v3`` checkpoints. Any document
        that raises the subject at all must also say that the pinned default does not need
        one, or a reader will conclude they have to accept a non-commercial licence.
        """
        text = self._text(relative)
        if "tabpfn" not in text.lower():
            pytest.skip(f"{relative} does not mention TabPFN")
        lowered = text.lower()
        raises_the_subject = any(
            phrase in lowered
            for phrase in ("license acceptance", "licence acceptance", "tabpfn_token", "api key")
        )
        if not raises_the_subject:
            return
        # Checked structurally rather than by matching an affirmative phrasing: a document
        # that actually explains the situation names the pinned version, and "no API key" /
        # "nor an API key" / "needs none" are all correct ways to say the same thing. Only
        # the version string is a reliable signal that the split is being described at all.
        from qbiocode.learning.compute_tabpfn import TABPFN_DEFAULT_VERSION

        assert TABPFN_DEFAULT_VERSION in lowered, (
            f"{relative} discusses a TabPFN token or licence acceptance without naming the "
            f"pinned default version ({TABPFN_DEFAULT_VERSION!r}), which needs neither. A "
            f"reader is left believing they must accept a non-commercial licence to use "
            f"TabPFN at all."
        )

    @pytest.mark.parametrize(
        "relative", ("docs/source/apps/config.md", "docs/source/installation.md")
    )
    def test_the_licence_difference_between_versions_is_documented(self, relative):
        """Choosing a model version is a licensing decision; both guides must say so."""
        text = self._text(relative).lower()
        assert "non-commercial" in text, (
            f"{relative} does not mention that the newer TabPFN checkpoints are "
            f"non-commercial, so nothing warns a reader off them"
        )
        assert "model_version" in text, f"{relative} does not name the model_version key"

    def test_the_documented_default_version_is_the_pinned_one(self):
        """Docs naming a default must name the one the code actually uses."""
        from qbiocode.learning.compute_tabpfn import TABPFN_DEFAULT_VERSION

        for relative in ("docs/source/apps/config.md", "docs/source/installation.md"):
            assert TABPFN_DEFAULT_VERSION in self._text(relative), (
                f"{relative} does not mention the pinned default model version "
                f"{TABPFN_DEFAULT_VERSION!r}"
            )

    def test_the_new_learners_reach_the_readme_and_the_conda_recipe(self):
        """Both list the classical baselines, and both were stale for a while."""
        for relative in ("README.md", "conda-recipe/meta.yaml"):
            text = self._text(relative).lower()
            for model in ("catboost", "tabpfn"):
                assert model in text, f"{relative} does not mention {model}"

    def test_the_sage_docs_list_every_sage_type(self):
        """``sage.rst`` documented only random_forest and mlp.

        It never mentioned ``xgboost_optuna`` either, so this was stale before CatBoost was
        added -- which is exactly why it needs a test rather than a careful reader. A user
        reading only the docs would not know two of the four surrogates existed.
        """
        source = (REPO_ROOT / "qbiocode" / "apps" / "sage" / "sage.py").read_text()
        block = source.split("valid_sage_types = [")[1].split("]")[0]
        declared = re.findall(r"'([a-z_]+)'", block)
        assert declared, "could not read valid_sage_types out of sage.py"
        docs = self._text("docs/source/apps/sage.rst")
        missing = [name for name in declared if name not in docs]
        assert not missing, (
            f"sage_types accepted by train_sub_sages but absent from "
            f"docs/source/apps/sage.rst: {missing}"
        )

    def test_the_sage_docs_list_every_classical_model_it_can_predict_for(self):
        """QSage learns from QProfiler results, so its model list must match the dispatch."""
        docs = self._text("docs/source/apps/sage.rst").lower()
        section = docs.split("**classical:**")[1].split("**quantum:**")[0]
        for model in ("xgboost", "catboost", "tabpfn"):
            assert model in section, (
                f"sage.rst's classical model list omits {model}, which QProfiler can run "
                f"and therefore QSage can be trained on"
            )

    def test_catboost_is_not_described_as_optional(self):
        """It is a core dependency; calling it an extra would send people to install it."""
        for relative in self.USER_FACING:
            text = self._text(relative)
            for phrase in ('pip install "qbiocode[catboost]"', "qbiocode[catboost]"):
                assert phrase not in text, (
                    f"{relative} refers to a [catboost] extra, which does not exist -- "
                    f"catboost is a base dependency"
                )
